version: 0.0
os: linux

files:
  - source: scripts/deploy.sh
    destination: /home/ubuntu/spring-github-action
    overwrite: yes
  - source: appspec.yml
    destination: /home/ubuntu/spring-github-action
    overwrite: yes
  - source: build/libs/OTTify-0.0.1-SNAPSHOT.jar
    destination: /home/ubuntu/spring-github-action
    overwrite: yes

permissions:
  - object: /
    owner: ubuntu
    group: ubuntu

hooks:
  ApplicationStart:
    - location: scripts/deploy.sh
      timeout: 60
      runas: ubuntu